apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ default (include "zulip-linear-bot.fullname" .) .Values.serviceAccount.name }}
  labels:
    {{- include "zulip-linear-bot.labels" . | nindent 4 }}
